# Generated by Django 4.2.19 on 2025-02-13 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='screenshots',
        ),
        migrations.CreateModel(
            name='ProductScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/', verbose_name='Скриншот')),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Порядковый номер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='shopapp.product')),
            ],
            options={
                'verbose_name': 'Скриншот продукта',
                'verbose_name_plural': 'Скриншоты продукта',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='productscreenshot',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_screenshot_order'),
        ),
    ]
