# Generated by Django 4.2.19 on 2025-02-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_remove_product_screenshots_productscreenshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscreenshot',
            name='image',
        ),
    ]
