# Generated by Django 4.2.19 on 2025-02-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_productscreenshot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscreenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/', verbose_name='Скриншот'),
        ),
    ]
