# Generated by Django 4.2.19 on 2025-02-14 07:28

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_productscreenshot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscreenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.ProductScreenshot.get_image_upload_path, verbose_name='Скриншот'),
        ),
    ]
