# Generated by Django 4.2.19 on 2025-02-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('PURCHASE_FAILED', 'Purchase Failed')], max_length=15),
        ),
    ]
