# Generated by Django 4.2.19 on 2025-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_balancetransaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Пополнение'), ('WITHDRAW', 'Списание'), ('PURCHASE_FAILED', 'Отказ в покупке'), ('PURCHASE_SUCCESS', 'Успешная покупка')], max_length=20),
        ),
    ]
