# Generated by Django 4.2.19 on 2025-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_balancetransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='game_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
